- name: Liệt kê IP các LIF trên NetApp Cluster
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap

  tasks:
    - name: Lấy thông tin các LIF
      na_ontap_info:
        hostname: "{{ ansible_host }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        https: true
      register: lif_info

    - name: In ra danh sách IP của các LIF
      debug:
        msg: |
          {% for lif in lif_info.ontap_info.interfaces %}
          LIF: {{ lif.interface_name }} - IP: {{ lif.address }} - Vserver: {{ lif.vserver }}
          {% endfor %}
