- name: Lấy phiên bản ONTAP từ cluster
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap

  tasks:
    - name: Thu thập thông tin phiên bản ONTAP
      na_ontap_rest_info:
        hostname: "{{ ontap_hostname }}"
        username: "{{ ontap_username }}"
        password: "{{ ontap_password }}"
        https: true
        validate_certs: false
        use_rest: always
        gather_subset:
          - cluster_node_info
        fields:
          - version
      register: ontap_info

    - name: In ra phiên bản ONTAP
      debug:
        msg: "{{ ontap_info }}"
