---
- name: Tạo user readonly trên ONTAP cluster
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap

  tasks:
    - name: Tạo người dùng mới với quyền readonly
      netapp.ontap.na_ontap_user:
        hostname: "{{ ontap_hostname }}"
        username: "{{ ontap_admin }}"
        password: "{{ ontap_password }}"
        https: true
        state: present
        name: "readonly_user"
        applications:
          - console
          - http
          - ontapi
          - ssh
        roles:
          - readonly
        authentication_method: password
        comment: "User chỉ có quyền đọc"
