- name: Tạo user readonly trên các cluster NetApp
  hosts: netapp_clusters
  gather_facts: no
  collections:
    - netapp.ontap

  tasks:
    - name: Tạo user readonly
      na_ontap_user:
        state: present
        name: readonly_user
        applications:
          - console
          - ssh
        authentication_method: password
        set_password: readonly_password123
        role_name: readonly
        hostname: "{{ ansible_host }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
